# Generated by Django 3.2.7 on 2021-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_socialmediaposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaposts',
            name='search_term',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
